export const birds = [
    { name: 'Crow', likes: 0 },
    { name: 'Peacock', likes: 0 },
    { name: 'Dove', likes: 0 },
    { name: 'Sparrow', likes: 0 },
    { name: 'Goose', likes: 0 },
    { name: 'Ostrich', likes: 0 },
    { name: 'Pigeon', likes: 0 },
    { name: 'Turkey', likes: 0 },
    { name: 'Hawk', likes: 0 },
    { name: 'Bald eagle', likes: 0 },
    { name: 'Raven', likes: 0 },
    { name: 'Parrot', likes: 0 },
    { name: 'Flamingo', likes: 0 },
    { name: 'Seagull', likes: 0 },
    { name: 'Swallow', likes: 0 },
    { name: 'Blackbird', likes: 0 },
    { name: 'Penguin', likes: 0 },
    { name: 'Robin', likes: 0 },
    { name: 'Swan', likes: 0 },
    { name: 'Owl', likes: 0 },
    { name: 'Stork', likes: 0 },
    { name: 'Woodpecker', likes: 0 },
  ];
  